<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="U:\Data\Data\Programming\Projects\NET_TestHarness\TestCases\TestCases.csproj" total="142" errors="0" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2012-07-01" time="19:46:00">
  <environment nunit-version="2.6.0.12051" clr-version="2.0.50727.5448" os-version="Microsoft Windows NT 6.1.7601 Service Pack 1" platform="Win32NT" cwd="U:\Data\Data\Programming\Projects\NET_TestHarness\TestCases" machine-name="MAIN-PC" user="Michael" user-domain="MAIN-PC" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite type="Project" name="U:\Data\Data\Programming\Projects\NET_TestHarness\TestCases\TestCases.csproj" executed="True" result="Success" success="True" time="11.590" asserts="0">
    <results>
      <test-suite type="Assembly" name="U:\Data\Data\Programming\Projects\NET_TestHarness\TestCases\bin\Debug\TestCases.dll" executed="True" result="Success" success="True" time="11.590" asserts="0">
        <results>
          <test-suite type="Namespace" name="TestCases" executed="True" result="Success" success="True" time="11.590" asserts="0">
            <results>
              <test-suite type="Namespace" name="ChkUtilsTests" executed="True" result="Success" success="True" time="0.919" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="ExceptionParserFactoryTests" executed="True" result="Success" success="True" time="0.015" asserts="0">
                    <results>
                      <test-case name="TestCases.ChkUtilsTests.ExceptionParserFactoryTests.DefaultExeptionParserFetch" executed="True" result="Success" success="True" time="0.001" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.ExceptionParserFactoryTests.ExeptionParserFetch" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.ExceptionParserFactoryTests.XmlExeptionParserFetch" executed="True" result="Success" success="True" time="0.005" asserts="1" />
                    </results>
                  </test-suite>
                  <test-suite type="TestFixture" name="ExceptionParserTests" executed="True" result="Success" success="True" time="0.017" asserts="0">
                    <results>
                      <test-case name="TestCases.ChkUtilsTests.ExceptionParserTests.DefaultExceptionParserTest" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ExceptionParserTests.ExceptionParserTest" executed="True" result="Success" success="True" time="0.002" asserts="6" />
                      <test-case name="TestCases.ChkUtilsTests.ExceptionParserTests.InnerExceptionParserTest" description="Test the recursive iteration through nested Exception Parsers" executed="True" result="Success" success="True" time="0.003" asserts="12" />
                      <test-case name="TestCases.ChkUtilsTests.ExceptionParserTests.XmlExceptionParserTest" executed="True" result="Success" success="True" time="0.001" asserts="12" />
                    </results>
                  </test-suite>
                  <test-suite type="TestFixture" name="SafeActionTests" executed="True" result="Success" success="True" time="0.019" asserts="0">
                    <results>
                      <test-case name="TestCases.ChkUtilsTests.SafeActionTests.DefaultObjectOnThrow" executed="True" result="Success" success="True" time="0.002" asserts="2" />
                      <test-case name="TestCases.ChkUtilsTests.SafeActionTests.NoExceptionPropagation" executed="True" result="Success" success="True" time="0.001" asserts="0" />
                      <test-case name="TestCases.ChkUtilsTests.SafeActionTests.ReturnsValidObj" executed="True" result="Success" success="True" time="0.001" asserts="1" />
                    </results>
                  </test-suite>
                  <test-suite type="TestFixture" name="StackFrameToolsTests" executed="True" result="Success" success="True" time="0.029" asserts="0">
                    <results>
                      <test-case name="TestCases.ChkUtilsTests.StackFrameToolsTests.ClassName_nullFrame" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.StackFrameToolsTests.ClassName_valid" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.StackFrameToolsTests.FileName_nullFrame" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.StackFrameToolsTests.FileName_OutOfBoundsIndex" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.StackFrameToolsTests.FirstNonWrappedMethod_caught" executed="True" result="Success" success="True" time="0.001" asserts="2" />
                      <test-case name="TestCases.ChkUtilsTests.StackFrameToolsTests.FirstNonWrappedMethod_nullType" executed="True" result="Success" success="True" time="0.001" asserts="2" />
                      <test-case name="TestCases.ChkUtilsTests.StackFrameToolsTests.FirstNonWrappedMethod_valid" executed="True" result="Success" success="True" time="0.000" asserts="2" />
                      <test-case name="TestCases.ChkUtilsTests.StackFrameToolsTests.LineNumber_nullFrame" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.StackFrameToolsTests.MethodName_nullFrame" executed="True" result="Success" success="True" time="0.001" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.StackFrameToolsTests.MethodName_valid" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                    </results>
                  </test-suite>
                  <test-suite type="TestFixture" name="ToErrorReportExceptionTests" executed="True" result="Success" success="True" time="0.071" asserts="0">
                    <results>
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportExceptionTests.OnAction_Exception" executed="True" result="Success" success="True" time="0.004" asserts="7" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportExceptionTests.OnAction_Exception_FinallyInvoked" executed="True" result="Success" success="True" time="0.001" asserts="8" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportExceptionTests.OnAction_Exception_MsgFormatInvoked" executed="True" result="Success" success="True" time="0.002" asserts="8" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportExceptionTests.OnAction_NoException" executed="True" result="Success" success="True" time="0.001" asserts="2" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportExceptionTests.OnAction_NoException_FinallyInvoked" executed="True" result="Success" success="True" time="0.001" asserts="3" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportExceptionTests.OnAction_NoException_MsgFormatInvoked" executed="True" result="Success" success="True" time="0.000" asserts="3" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportExceptionTests.OnFunction_Exception" executed="True" result="Success" success="True" time="0.003" asserts="8" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportExceptionTests.OnFunction_Exception_FinallyInvoked" executed="True" result="Success" success="True" time="0.002" asserts="9" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportExceptionTests.OnFunction_Exception_MsgFormatInvoked" executed="True" result="Success" success="True" time="0.002" asserts="9" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportExceptionTests.OnFunction_Exception_NoLogging" executed="True" result="Success" success="True" time="0.001" asserts="8" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportExceptionTests.OnFunction_NoException" executed="True" result="Success" success="True" time="0.001" asserts="3" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportExceptionTests.OnFunction_NoException_FinallyInvoked" executed="True" result="Success" success="True" time="0.000" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportExceptionTests.OnFunction_NoException_MsgFormatInvoked" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                    </results>
                  </test-suite>
                  <test-suite type="TestFixture" name="ToErrorReportFaultExceptionTests" executed="True" result="Success" success="True" time="0.104" asserts="0">
                    <results>
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportFaultExceptionTests.OnAction_Exception" executed="True" result="Success" success="True" time="0.040" asserts="7" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportFaultExceptionTests.OnAction_Exception_FinallyInvoked" executed="True" result="Success" success="True" time="0.001" asserts="8" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportFaultExceptionTests.OnAction_Exception_MsgFormatInvoked" executed="True" result="Success" success="True" time="0.001" asserts="8" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportFaultExceptionTests.OnAction_NoException" executed="True" result="Success" success="True" time="0.000" asserts="2" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportFaultExceptionTests.OnAction_NoException_FinallyInvoked" executed="True" result="Success" success="True" time="0.000" asserts="3" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportFaultExceptionTests.OnAction_NoException_MsgFormatInvoked" executed="True" result="Success" success="True" time="0.001" asserts="3" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportFaultExceptionTests.OnFunction_Exception" executed="True" result="Success" success="True" time="0.003" asserts="8" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportFaultExceptionTests.OnFunction_Exception_FinallyInvoked" executed="True" result="Success" success="True" time="0.002" asserts="9" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportFaultExceptionTests.OnFunction_Exception_MsgFormatInvoked" executed="True" result="Success" success="True" time="0.002" asserts="9" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportFaultExceptionTests.OnFunction_Exception_NoLogging" executed="True" result="Success" success="True" time="0.001" asserts="8" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportFaultExceptionTests.OnFunction_NoException" executed="True" result="Success" success="True" time="0.001" asserts="3" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportFaultExceptionTests.OnFunction_NoException_FinallyInvoked" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrorReportFaultExceptionTests.OnFunction_NoException_MsgFormatInvoked" executed="True" result="Success" success="True" time="0.000" asserts="4" />
                    </results>
                  </test-suite>
                  <test-suite type="TestFixture" name="ToErrReportTests" executed="True" result="Success" success="True" time="0.058" asserts="0">
                    <results>
                      <test-case name="TestCases.ChkUtilsTests.ToErrReportTests.Action_Caught_ErrReportException" executed="True" result="Success" success="True" time="0.001" asserts="8" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrReportTests.Action_Caught_Exception_ErrorFormater" executed="True" result="Success" success="True" time="0.002" asserts="6" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrReportTests.Action_Caught_Exception_SimpleString" executed="True" result="Success" success="True" time="0.000" asserts="6" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrReportTests.Action_Caught_FaultException" executed="True" result="Success" success="True" time="0.001" asserts="8" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrReportTests.Action_Valid" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrReportTests.Action_Valid_ConfirmMsgFormaterNotInvoked" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrReportTests.Action_Valid_FinallyExceptionCaught" executed="True" result="Success" success="True" time="0.001" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrReportTests.Func_Caught_ErrReportException" executed="True" result="Success" success="True" time="0.002" asserts="8" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrReportTests.Func_Caught_Exception_ErrorFormater" executed="True" result="Success" success="True" time="0.001" asserts="6" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrReportTests.Func_Caught_Exception_SimpleString" executed="True" result="Success" success="True" time="0.001" asserts="6" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrReportTests.Func_Caught_FaultException" executed="True" result="Success" success="True" time="0.001" asserts="8" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrReportTests.Func_Valid" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrReportTests.Func_Valid_ConfirmMsgFormaterNotInvoked" executed="True" result="Success" success="True" time="0.001" asserts="0" />
                      <test-case name="TestCases.ChkUtilsTests.ToErrReportTests.Func_Valid_FinallyExceptionCaught" executed="True" result="Success" success="True" time="0.002" asserts="1" />
                    </results>
                  </test-suite>
                  <test-suite type="TestFixture" name="ValidatorTests" executed="True" result="Success" success="True" time="0.141" asserts="0">
                    <results>
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.Disposed_Fail" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.Disposed_Fail_FaultException" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.Disposed_Valid" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.Disposed_Valid_FaultException" executed="True" result="Success" success="True" time="0.001" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.ExceptionType_Fault_False" executed="True" result="Success" success="True" time="0.001" asserts="0" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.ExceptionType_Fault_Param" executed="True" result="Success" success="True" time="0.001" asserts="0" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.ExceptionType_Fault_StringEmpty" executed="True" result="Success" success="True" time="0.002" asserts="0" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.ExceptionType_Fault_StringNull" executed="True" result="Success" success="True" time="0.001" asserts="0" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.ExceptionType_Fault_True" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.ExceptionType_Fault_Var" executed="True" result="Success" success="True" time="0.001" asserts="0" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.ExceptionType_Regular_False" executed="True" result="Success" success="True" time="0.001" asserts="0" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.ExceptionType_Regular_Param" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.ExceptionType_Regular_String_Empty" executed="True" result="Success" success="True" time="0.001" asserts="0" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.ExceptionType_Regular_String_Null" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.ExceptionType_Regular_True" executed="True" result="Success" success="True" time="0.001" asserts="0" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.ExceptionType_Regular_Var" executed="True" result="Success" success="True" time="0.001" asserts="0" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.False_Fail" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.False_Fail_FaultException" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.False_Valid" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.False_Valid_FaultException" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.Param_NullArg" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.Param_NullArg_FaultException" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.Param_ValidArg" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.Param_ValidArg_FaultException" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.String_Empty" executed="True" result="Success" success="True" time="0.002" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.String_Empty_FaultException" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.String_Null" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.String_Null_FaultException" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.True_Fail" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.True_Fail_FaultException" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.True_Valid" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.True_Valid_FaultException" executed="True" result="Success" success="True" time="0.001" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.Var_NullArg" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.Var_NullArg_FaultException" executed="True" result="Success" success="True" time="0.001" asserts="4" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.Var_ValidArg" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.ChkUtilsTests.ValidatorTests.Var_ValidArg_FaultException" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite type="Namespace" name="LogUtilsTests" executed="True" result="Success" success="True" time="4.573" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="LogTests" executed="True" result="Success" success="True" time="4.534" asserts="0">
                    <results>
                      <test-case name="TestCases.LogUtilsTests.LogTests.Critical_Restricted" executed="True" result="Success" success="True" time="0.502" asserts="12" />
                      <test-case name="TestCases.LogUtilsTests.LogTests.Critical_Valid" executed="True" result="Success" success="True" time="0.251" asserts="6" />
                      <test-case name="TestCases.LogUtilsTests.LogTests.Debug_Restricted" executed="True" result="Success" success="True" time="0.500" asserts="12" />
                      <test-case name="TestCases.LogUtilsTests.LogTests.Debug_Valid" executed="True" result="Success" success="True" time="0.250" asserts="6" />
                      <test-case name="TestCases.LogUtilsTests.LogTests.Error_Restricted" executed="True" result="Success" success="True" time="0.500" asserts="12" />
                      <test-case name="TestCases.LogUtilsTests.LogTests.Error_Valid" executed="True" result="Success" success="True" time="0.250" asserts="6" />
                      <test-case name="TestCases.LogUtilsTests.LogTests.Exception_Restricted" executed="True" result="Success" success="True" time="0.501" asserts="12" />
                      <test-case name="TestCases.LogUtilsTests.LogTests.Exception_Valid" executed="True" result="Success" success="True" time="0.251" asserts="6" />
                      <test-case name="TestCases.LogUtilsTests.LogTests.Info_Restricted" executed="True" result="Success" success="True" time="0.501" asserts="12" />
                      <test-case name="TestCases.LogUtilsTests.LogTests.Info_Valid" executed="True" result="Success" success="True" time="0.250" asserts="6" />
                      <test-case name="TestCases.LogUtilsTests.LogTests.Warning_Restricted" executed="True" result="Success" success="True" time="0.501" asserts="12" />
                      <test-case name="TestCases.LogUtilsTests.LogTests.Warning_Valid" executed="True" result="Success" success="True" time="0.250" asserts="6" />
                    </results>
                  </test-suite>
                  <test-suite type="TestFixture" name="MsgLevelTests" executed="True" result="Success" success="True" time="0.024" asserts="0">
                    <results>
                      <test-case name="TestCases.LogUtilsTests.MsgLevelTests.GreaterOrEqual_Debug_Debug" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.LogUtilsTests.MsgLevelTests.GreaterOrEqual_Debug_Info" executed="True" result="Success" success="True" time="0.001" asserts="1" />
                      <test-case name="TestCases.LogUtilsTests.MsgLevelTests.GreaterOrEqual_Debug_Warning" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.LogUtilsTests.MsgLevelTests.ShortName_Critical" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.LogUtilsTests.MsgLevelTests.ShortName_Debug" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.LogUtilsTests.MsgLevelTests.ShortName_Error" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.LogUtilsTests.MsgLevelTests.ShortName_Exception" executed="True" result="Success" success="True" time="0.001" asserts="1" />
                      <test-case name="TestCases.LogUtilsTests.MsgLevelTests.ShortName_Info" executed="True" result="Success" success="True" time="0.000" asserts="1" />
                      <test-case name="TestCases.LogUtilsTests.MsgLevelTests.ShortName_Warning" executed="True" result="Success" success="True" time="0.001" asserts="1" />
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite type="Namespace" name="SpStateMachineTests" executed="True" result="Success" success="True" time="6.065" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="SimpleEventListnerTests" executed="True" result="Success" success="True" time="0.420" asserts="0">
                    <results>
                      <test-case name="TestCases.SpStateMachineTests.SimpleEventListnerTests.MessageReceived_NoSubscribers" executed="True" result="Success" success="True" time="0.002" asserts="0" />
                      <test-case name="TestCases.SpStateMachineTests.SimpleEventListnerTests.MessageReceived_validMsg" executed="True" result="Success" success="True" time="0.201" asserts="4" />
                      <test-case name="TestCases.SpStateMachineTests.SimpleEventListnerTests.ResponseReceived_NoSubscribers" executed="True" result="Success" success="True" time="0.001" asserts="0" />
                      <test-case name="TestCases.SpStateMachineTests.SimpleEventListnerTests.ResponseReceived_validMsg" executed="True" result="Success" success="True" time="0.201" asserts="4" />
                    </results>
                  </test-suite>
                  <test-suite type="TestFixture" name="SpStateMachineTests" executed="True" result="Success" success="True" time="3.850" asserts="0">
                    <results>
                      <test-case name="TestCases.SpStateMachineTests.SpStateMachineTests._0_Dispose_MultiDisposeSafe" executed="True" result="Success" success="True" time="0.504" asserts="4" />
                      <test-case name="TestCases.SpStateMachineTests.SpStateMachineTests._0_DisposeObject_Success" executed="True" result="Success" success="True" time="0.026" asserts="0" />
                      <test-case name="TestCases.SpStateMachineTests.SpStateMachineTests._50050_SpStateMachineEngine_nullListner" executed="True" result="Success" success="True" time="0.004" asserts="5" />
                      <test-case name="TestCases.SpStateMachineTests.SpStateMachineTests._50051_SpStateMachineEngine_nullStore" executed="True" result="Success" success="True" time="0.001" asserts="5" />
                      <test-case name="TestCases.SpStateMachineTests.SpStateMachineTests._50052_SpStateMachineEngine_nullBehavior" executed="True" result="Success" success="True" time="0.018" asserts="5" />
                      <test-case name="TestCases.SpStateMachineTests.SpStateMachineTests._50053_SpStateMachineEngine_nullStateMachine" executed="True" result="Success" success="True" time="0.005" asserts="5" />
                      <test-case name="TestCases.SpStateMachineTests.SpStateMachineTests._50054_SpStateMachineEngine_nullTimer" executed="True" result="Success" success="True" time="0.004" asserts="5" />
                      <test-case name="TestCases.SpStateMachineTests.SpStateMachineTests._50056_StartDisposed" executed="True" result="Success" success="True" time="0.520" asserts="5" />
                      <test-case name="TestCases.SpStateMachineTests.SpStateMachineTests._50057_StopDisposed" executed="True" result="Success" success="True" time="0.505" asserts="5" />
                      <test-case name="TestCases.SpStateMachineTests.SpStateMachineTests._50058_DriverThreadUnexpectedError" executed="True" result="Success" success="True" time="0.675" asserts="4" />
                      <test-case name="TestCases.SpStateMachineTests.SpStateMachineTests._50060_DisposeObject_ErrorDisposingInternalObjects" executed="True" result="Success" success="True" time="0.509" asserts="4" />
                    </results>
                  </test-suite>
                  <test-suite type="TestFixture" name="StateMachineScratchPad" executed="True" result="Inconclusive" success="False" time="0.004" asserts="0" />
                  <test-suite type="TestFixture" name="WinSimplePeriodicTimerTests" executed="True" result="Success" success="True" time="1.762" asserts="0">
                    <results>
                      <test-case name="TestCases.SpStateMachineTests.WinSimplePeriodicTimerTests._0_SetInterval_OK" executed="True" result="Success" success="True" time="0.001" asserts="0" />
                      <test-case name="TestCases.SpStateMachineTests.WinSimplePeriodicTimerTests._0_Start_Multi" executed="True" result="Success" success="True" time="0.003" asserts="0" />
                      <test-case name="TestCases.SpStateMachineTests.WinSimplePeriodicTimerTests._0_Stop_Multi" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                      <test-case name="TestCases.SpStateMachineTests.WinSimplePeriodicTimerTests._50000_SetInterval_ZeroTimespan" executed="True" result="Success" success="True" time="0.001" asserts="5" />
                      <test-case name="TestCases.SpStateMachineTests.WinSimplePeriodicTimerTests._50002_SetInterval_Disposed" executed="True" result="Success" success="True" time="0.001" asserts="5" />
                      <test-case name="TestCases.SpStateMachineTests.WinSimplePeriodicTimerTests._50003_Start_Disposed" executed="True" result="Success" success="True" time="0.001" asserts="5" />
                      <test-case name="TestCases.SpStateMachineTests.WinSimplePeriodicTimerTests._50005_Start_Disposed" executed="True" result="Success" success="True" time="0.001" asserts="5" />
                      <test-case name="TestCases.SpStateMachineTests.WinSimplePeriodicTimerTests.MultiDispose" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                      <test-case name="TestCases.SpStateMachineTests.WinSimplePeriodicTimerTests.OnWakeup_noSubscribers" executed="True" result="Success" success="True" time="0.200" asserts="0" />
                      <test-case name="TestCases.SpStateMachineTests.WinSimplePeriodicTimerTests.OnWakeup_PulseCount" executed="True" result="Success" success="True" time="1.501" asserts="1" />
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite type="TestFixture" name="TestHelperTests" executed="True" result="Inconclusive" success="False" time="0.004" asserts="0" />
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>